version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    env_file:
      - ./.env